version: '3'
services:

  monitor_1:
    container_name: monitor_1
    image: monitor:latest
    entrypoint: python3 /main.py
    restart: on-failure
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./storage:/states
    environment:
      - INTERNAL_PORT=3003
      - TIMEOUT=10
      - ID=monitor_1
      - MONITOR_IPS=monitor_1,monitor_2,monitor_3
      - MONITOR_PORT=3003
      - ELECTION_PORT=3004
      - LEADER_INFO_PORT=3002
      - LEADER=2
      - IS_LEADER=False
    depends_on:
      - monitor_3

  monitor_2:
    container_name: monitor_2
    image: monitor:latest
    entrypoint: python3 /main.py
    restart: on-failure
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./storage:/states
    environment:
      - INTERNAL_PORT=3003
      - TIMEOUT=10
      - ID=monitor_2
      - MONITOR_IPS=monitor_1,monitor_2,monitor_3
      - MONITOR_PORT=3003
      - ELECTION_PORT=3004
      - LEADER_INFO_PORT=3002
      - LEADER=2
      - IS_LEADER=False
    depends_on:
      - monitor_3

  monitor_3:
    container_name: monitor_3
    image: monitor:latest
    entrypoint: python3 /main.py
    restart: on-failure
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./storage:/states
    environment:
      - INTERNAL_PORT=3003
      - TIMEOUT=10
      - ID=monitor_3
      - MONITOR_IPS=monitor_1,monitor_2,monitor_3
      - MONITOR_PORT=3003
      - ELECTION_PORT=3004
      - LEADER_INFO_PORT=3002
      - LEADER=2
      - IS_LEADER=True

volumes:
  storage:
