version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - 15672:15672
      - 5672:5672

  monitor_1:
    container_name: monitor_1
    image: monitor:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./storage:/states
    links: 
      - rabbitmq
    environment:
      - INTERNAL_PORT=3003
      - TIMEOUT=10
      - ID=monitor_1

  monitor_2:
    container_name: monitor_2
    image: monitor:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./storage:/states
    links: 
      - rabbitmq
    environment:
      - INTERNAL_PORT=3003
      - TIMEOUT=10
      - ID=monitor_2

  filter_avg_rating_server_duration_1:
    container_name: filter_avg_rating_server_duration_1
    image: filter_avg_rating_server_duration:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
      - monitor_1
      - monitor_2
    links: 
      - rabbitmq
    environment:
      - MATCH_QUEUE=filter_arsd_queue
      - OUTPUT_QUEUE=output_queue_1
      - AVG_RATING_FIELD=average_rating
      - SERVER_FIELD=server
      - DURATION_FIELD=duration
      - ID_FIELD=token
      - INTERFACE_IP=interface
      - INTERFACE_PORT=3001
      - MONITOR_IPS=monitor_1,monitor_2
      - MONITOR_PORT=3003
      - FREQUENCY=3
      - ID=filter_avg_rating_server_duration_1

  interface:
    container_name: interface
    image: interface:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
      - monitor_1
      - monitor_2
    volumes: 
      - ./storage:/states
    links: 
      - rabbitmq
    environment:
      - API_PORT=3002
      - SENTINEL_AMOUNT=4
      - INTERNAL_PORT=3001
      - MONITOR_IPS=monitor_1,monitor_2
      - MONITOR_PORT=3003
      - FREQUENCY=3
      - ID=interface

volumes:
  storage:
